name: Cypress Cucumber Tests
on:
  push:
  pull_request:
    types: [opened]

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start

      - name: Generate report
        run: cd cypress-cucumber && npm run report
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-cucumber-report
          path: cypress-cucumber/cypress/cucumber-report/
